name: yuka_clone
description: A clone of the Yuka app in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: '^3.0.0+1'

  gradient_app_bar: '^0.0.1'
  gradient_widgets: '^0.5.0'

  firebase_core: '^0.2.5'
  fast_qr_reader_view: '^0.1.5'

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - res/drawables/
    - res/fonts/

  fonts:
    - family:  icons
      fonts:
       - asset: res/fonts/icons.ttf