import 'package:flutter/material.dart';
import 'package:yuka_clone/ui/resources/colors.dart';

class AppStyle {
  const AppStyle._();

  static TextTheme get textTheme => const TextTheme(
        display4: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        display3: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        display2: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        display1: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        headline: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        title: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        subhead: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        body2: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        body1: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        caption: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        button: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        subtitle: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
        overline: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.dark_text,
            decoration: TextDecoration.none),
      );

  static TextTheme get lightTextTheme => const TextTheme(
        display4: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        display3: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        display2: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        display1: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        headline: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        title: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        subhead: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        body2: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        body1: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        caption: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        button: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        subtitle: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
        overline: TextStyle(
            fontFamily: 'Roboto',
            inherit: true,
            color: AppColors.light_text,
            decoration: TextDecoration.none),
      );
}
